### ISSUE TITLE
[Request] Make deb of the tweak available on repo

### ISSUE THREAD

**Issue by enaloha** [denialpan/DoABarrelWall#11]
As the title says, it would awesome if the tweak could be put on a repo (the one mentioned in the Readme does not list any packages at all).

**Comment by denialpan** [comment]
You can now directly download the .deb [here](https://github.com/denialpan/DoABarrelWall/releases/tag/v0.0.4), and manually install it yourself if you are having trouble accessing it from my repository.

This is the same version that I have in the repository and has not been touched. This does not have rootless support at the moment.

**Comment by enaloha** [comment]
When I saw the commit, I was hoping for a rootless version. Are you planning to compile a rootless one? 
-Reinhold

**Comment by denialpan** [comment]
There is a new release now [here](https://github.com/denialpan/DoABarrelWall/releases/tag/v0.0.3-26) with rootless support added by https://github.com/MrGcGamer. Although, I am unsure if you are able to use it at the moment, as this requires a version of Cephei that has not be publicly released yet.

**Comment by enaloha** [comment]
thank you so much. I know there is a leaked Cephei version and the official release is supposed to happen any day now.
