### ISSUE TITLE
What part to download and install

### ISSUE THREAD

**Issue by midnight12346** [denialpan/DoABarrelWall#2]
What part do I download and install im quite new to jailbreaking

**Comment by denialpan** [comment]
Lucky you caught me right before I went to bed :)

If you're familiar enough with jailbreaking to know how to install tweaks, just add this [link](https://denialpan.github.io/) into your package manager.

If, however, you're not with familiar with jailbreaking, I suggest you join this [discord server](https://discord.gg/jb) to receive better help. Upon joining, ask if your device is able to be jailbroken. If it isn't, there is unfortunately nothing else I can do for you :(

Hope you have a good rest of your day, good night.
