### ISSUE TITLE
“DoABarrelWall” interferes with tweak “Flow”

### ISSUE THREAD

**Issue by drossosc** [denialpan/DoABarrelWall#7]
Once installing “DoABarrelWall”, it will force the wallpaper over the tweak “Flow” (by Muirey03 on Packix repo) which shows a blurred image of the active songs cover art.

I’m not sure what to do to combat this and have the wallpaper from “Flow” be active instead of “DoABarrelWall”

For reference:
![1505A7EA-714F-4C46-92C9-5E76D99CE5F5](https://user-images.githubusercontent.com/72714109/117570439-79bc3200-b10d-11eb-8660-35276087d81b.png)Both Flow and DoABarrelWall active

![002D7214-DD7A-4CC2-8575-9F9ADF11338F](https://user-images.githubusercontent.com/72714109/117570508-b6882900-b10d-11eb-8362-349f633e21ae.png)
Flow running without DoABarrelWall active

**Comment by denialpan** [comment]
Thank you for the detailed explanation of what was happening, I appreciate it 👍 

It seems that my tweak is incompatible with Flow, where my wallpaper is displayed on a higher layer than what the developer of Flow intended to show the album art. I currently don't have a solution to this, in fact, this tweak also most likely conflicts with other lockscreen tweaks that act to change the background.

For now, I suggest disabling my tweak if it becomes too irritating for you, my apologies that I can't help with this tweak conflict :(

Have a good rest of your evening.

**Comment by Luki120** [comment]
I just saw this yesterday poping by your GH :eyes: All I can think of is maybe make an inline if to check if media is playing *and* if flow tweak is installed, only then insert DoABarrelWall view a few indexes behind, idk 1 or 2, else, what you're doing now. Idk if it'll work or not though because I don't have that tweak so I can't test it, but in mine mind that makes sense haha.

**Comment by denialpan** [comment]
Ahh, thanks for the suggestion! I know that adding a check for determining whether the music player is active and if Flow is installed is easy, but I'm not sure if changing the index will result to anything, given that it is already at the lowest z-index possible of `insertSubview:wallpaperImageViewLS atIndex:0`. Do correct me if I have this reversed, if `0` is instead the highest layer possible; and of course, if you know a certain way to resolve it, you can make a pull request and I can look at it 🍉.

**Comment by Luki120** [comment]
You're correct, index at starts at 0, but the logic is reversed I think(? because if you place your view at index 0, it'll show above everything, so what I'm thinking is that if you place it at either 1 or 2, Flow view should show up and yours be covered.
